# Generated by Django 5.1.4 on 2024-12-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('agency_or_private_landlord', models.CharField(max_length=100)),
                ('agency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
