# Generated by Django 5.1.4 on 2024-12-16 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_reviews', '0002_address_review_delete_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental_reviews.address'),
            preserve_default=False,
        ),
    ]
